# Site settings
title: Travis-folio
email: twaelbroeck@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl: # the subpath of your site, e.g. /blog/
url: https://travs-w.github.io # the base hostname & protocol for your site
github_username:  travs-w
linkedin_username: traviswaelbroeck
twitter_username: travs_w

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

categories: {'odoo', 'magento', 'other'}

collections:
  blog:
    output: true
    permalink: /blog/:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/
